export const LOAD_DOC = 'LOAD_DOC'
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'
export const STOP = 'STOP'
export const SUCCESS = 'SUCCESS'

export const SET_TEMPO = 'SET_TEMPO'
export const SET_NUM_MEASURES = 'SET_NUM_MEASURES'
export const TOGGLE_METRONOME = 'TOGGLE_METRONOME'
export const tempo = 'tempo'
export const numMeasures = 'numMeasures'
export const metronomeEnabled = 'metronomeEnabled'
